proton-ge-bin: make $out provide an error when added to an env
This package should never be added to systemPackages or other global
environments as it will not provide any function there. Making its $out a file
will prevent buildEnv from including it; providing an error like this:

error: The store path /nix/store/wxl3m27dmjjsfqvzzxw7ibr0gr54wwkp-proton-ge-bin-GE-Proton9-1 is a file and can't be merged into an environment using pkgs.buildEnv! at /nix/store/ndhb3bsaf3zc6gx22vjl0w11sxvapf7b-builder.pl line 122.

Some breadcrumbs are left inside the file.

(cherry picked from commit 74c55dbb254680170610c931fb839966d7c0bad2)