mozillavpn: add qtwayland to build inputs
This fixes the app not launching in a wayland environment.
❯ mozillavpn
Aborted (core dumped)

~/.local/share/mozillavpn.log showed:
Warning: Could not find the Qt platform plugin "wayland" in ""
Error: This application failed to start because no Qt platform plugin could be initialized.
Reinstalling the application may fix this problem.
Available platform plugins are: linuxfb, minimal, eglfs, minimalegl, vkkhrdisplay, xcb, vnc, offscreen.

(cherry picked from commit 22143317c12b6a8ea90d1f873b8c423dd40ed2cd)